var domicilio="Img/domicilio.png"
var asporto="Img/asporto.png"
var tavolo="Img/tavolo.png"
var ombrellone="Img/ombrellone.png"
var error="Img/error.png"
var prodotti="Img/prodotti.png"  
var prenotazione=""
var call="Img/telephone.png"
